### ISSUE TITLE
Сделать макеты страниц

### ISSUE THREAD

**Issue by Coll4pse** [Antiplusists/Cardsetta#1]
Накидать макеты страниц в каком-нибудь редакторе. Например Figma, Photoshop.

**Comment by Todti-I** [comment]
https://www.figma.com/file/l8fbZua4ktSQiheZLiIoLM

Demo: https://www.figma.com/proto/l8fbZua4ktSQiheZLiIoLM

**Comment by Coll4pse** [comment]
Макеты:
* [Figma](https://www.figma.com/file/l8fbZua4ktSQiheZLiIoLM/Layout?node-id=0%3A1)
* [Figma preview](https://www.figma.com/proto/l8fbZua4ktSQiheZLiIoLM/Layout?node-id=91%3A240&scaling=contain&page-id=0%3A1)
